services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      MONGO_URI: ${MONGO_URI}
      JWT_SECRET: ${JWT_SECRET}
      CODE_RUNNER_URL: ${CODE_RUNNER_URL}
    depends_on:
      mongodb:
        condition: service_healthy
      code-runner:
        condition: service_started
    networks:
      - devsphere-net
    env_file:
      - .env

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - devsphere-net

  mongodb:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - devsphere-net

  code-runner:
    build:
      context: ./code-runner
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - devsphere-net
    env_file:
      - .env

volumes:
  mongo_data:

networks:
  devsphere-net:
    driver: bridge
